In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F # Will allow us to move our data forward in our function



In [27]:
# Create a model class that inherits nn.Module
class simple_model(nn.Module):
    # input layer(4 features of the flower)--> 
    # Hidden layer1-->
    # Hidden layer2-->
    # Output(3 classes of iris flower)
    
    def  __init__(self, input_features=4, h1=8, h2=9, output_features=3):
        super().__init__() # Instantiate our nn.Module
        self.fc1 = nn.Linear(input_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, output_features)
    
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.out(x))
        
        return x
    
    
    

In [28]:
# Pick a manual seed for randomization
torch.manual_seed(32)
# Create a instant model
model = simple_model()

In [29]:
import pandas as pd
import matplotlib.pyplot as plt

In [30]:
# import the iris dataset from scikit-learn's dataset module
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()

In [31]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [36]:
# Trsin test split , set x,y
x = iris.data # features
y = iris.target # targets

In [37]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [38]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
# Train Test Split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=32)

In [42]:
# Convert x features from numpy array to  float tensors
x_train_tensor = torch.FloatTensor(x_train)
x_test_tensor = torch.FloatTensor(x_test)


In [45]:
x_train_tensor

tensor([[5.7000, 2.6000, 3.5000, 1.0000],
        [4.4000, 3.0000, 1.3000, 0.2000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [5.5000, 3.5000, 1.3000, 0.2000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [6.4000, 3.1000, 5.5000, 1.8000],
        [5.7000, 2.9000, 4.2000, 1.3000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [7.1000, 3.0000, 5.9000, 2.1000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        [5.4000, 3.9000, 1.7000, 0.4000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [6.2000, 2.9000, 4.3000, 1.3000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [6.1000, 3.0000, 4.6000, 1.4000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [4.9000, 2.5000, 4.5000, 1

In [46]:
x_test_tensor

tensor([[5.7000, 2.8000, 4.5000, 1.3000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [6.1000, 2.6000, 5.6000, 1.4000],
        [7.9000, 3.8000, 6.4000, 2.0000],
        [5.1000, 3.3000, 1.7000, 0.5000],
        [4.9000, 3.1000, 1.5000, 0.2000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [6.8000, 2.8000, 4.8000, 1.4000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [6.5000, 3.0000, 5.2000, 2.0000],
        [5.7000, 2.5000, 5.0000, 2.0000],
        [5.6000, 3.0000, 4.5000, 1.5000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [5.6000, 2.5000, 3.9000, 1.1000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [6.0000, 3.0000, 4.8000, 1.8000],
        [4.8000, 3.0000, 1.4000, 0

In [47]:
# Convert y targets from numpy array to tensors long
y_train_tensor = torch.LongTensor(y_train)
y_test_tensor = torch.LongTensor(y_test)

In [48]:
y_train_tensor

tensor([1, 0, 0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 0, 2, 0, 2, 1, 1, 1, 0, 1, 1, 0, 2,
        1, 0, 0, 0, 0, 1, 2, 2, 1, 1, 2, 2, 0, 2, 0, 0, 2, 0, 2, 0, 2, 0, 1, 0,
        0, 1, 1, 2, 0, 1, 0, 1, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2, 1, 2, 0, 2, 2, 2,
        0, 2, 1, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 2, 0, 2, 1, 2, 2, 1, 1, 0, 1,
        2, 2, 1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 0])

In [49]:
y_test_tensor

tensor([1, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2, 0,
        0, 1, 0, 2, 0, 0])